In [22]:
import pandas as pd

import zipfile
from pathlib import Path

In [13]:
project_path = Path("..")
zip_path = project_path / "ecommerce_dataset.zip"
raw_path = project_path / "data" / "raw"

In [14]:
raw_path.mkdir(parents = True, exist_ok = True)

In [16]:
type(raw_path)

pathlib.WindowsPath

In [17]:
with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(raw_path)

In [18]:
list(raw_path.iterdir())

[WindowsPath('../data/raw/customers.csv'),
 WindowsPath('../data/raw/monthly_revenue.csv'),
 WindowsPath('../data/raw/orders.csv'),
 WindowsPath('../data/raw/product_summary.csv')]

In [20]:
csv_files = list(raw_path.glob("*.csv"))
csv_files

[WindowsPath('../data/raw/customers.csv'),
 WindowsPath('../data/raw/monthly_revenue.csv'),
 WindowsPath('../data/raw/orders.csv'),
 WindowsPath('../data/raw/product_summary.csv')]

In [23]:
dataframes = {}

for file in csv_files:
    dataframes[file.stem] = pd.read_csv(file)

In [24]:
dataframes.keys()

dict_keys(['customers', 'monthly_revenue', 'orders', 'product_summary'])

In [25]:
for name, df in dataframes.items():
    print(name, df.shape)

customers (8000, 20)
monthly_revenue (75, 10)
orders (25000, 28)
product_summary (140, 9)

In [27]:
for name, df in dataframes.items():
    print(f"\n{name.upper()}")
    print(df.columns.tolist())

CUSTOMERS
['customer_id', 'country', 'age', 'gender', 'membership_tier', 'registration_date', 'total_orders', 'total_spend_usd', 'avg_order_value_usd', 'days_since_last_purchase', 'preferred_category', 'preferred_device', 'preferred_payment_method', 'acquisition_channel', 'reviews_given', 'avg_review_score', 'returns_made', 'wishlist_items', 'newsletter_subscribed', 'churned']

MONTHLY_REVENUE
['year', 'month', 'quarter', 'orders', 'revenue_usd', 'avg_order_value', 'avg_discount_pct', 'return_rate', 'unique_customers', 'new_customers']

ORDERS
['order_id', 'customer_id', 'order_date', 'year', 'month', 'quarter', 'day_of_week', 'product_name', 'category', 'unit_price_usd', 'quantity', 'subtotal_usd', 'discount_pct', 'discount_amount_usd', 'shipping_fee_usd', 'tax_pct', 'tax_amount_usd', 'total_amount_usd', 'payment_method', 'device_used', 'delivery_days', 'delivery_date', 'order_status', 'returned', 'customer_rating', 'session_duration_minutes', 'pages_viewed_before_purchase', 'is_repeat_customer']

PRODUCT_SUMMARY
['category', 'product_name', 'total_orders', 'total_revenue_usd', 'avg_price', 'avg_rating', 'return_rate', 'avg_discount_pct', 'avg_delivery_days']

In [28]:
for name, df in dataframes.items():
    print(f"\n{name.upper()}")
    display(df.head())

CUSTOMERS

,customer_id,country,age,gender,membership_tier,registration_date,total_orders,total_spend_usd,avg_order_value_usd,days_since_last_purchase,preferred_category,preferred_device,preferred_payment_method,acquisition_channel,reviews_given,avg_review_score,returns_made,wishlist_items,newsletter_subscribed,churned
0,C00001,United States,40,Male,Free,2019-01-17,4,286.63,63.78,49,Food & Grocery,Mobile,Debit Card,Social Media,1,4.5,0,12,0,0
1,C00002,United States,20,Female,Free,2026-03-04,11,1245.18,107.32,126,Toys & Games,Mobile,Debit Card,Organic Search,2,2.6,1,1,0,0
2,C00003,United States,43,Female,Gold,2026-02-08,4,195.37,42.74,0,Home & Kitchen,Mobile,PayPal,Referral,0,4.8,0,0,1,0
3,C00004,United States,41,Male,Free,2025-03-19,6,99.45,15.61,6,Electronics,Desktop,PayPal,Organic Search,2,4.2,0,8,1,0
4,C00005,France,37,Other,Platinum,2024-09-10,36,2593.21,79.09,161,Clothing & Apparel,Tablet,Debit Card,Social Media,9,4.0,4,5,1,0

MONTHLY_REVENUE

,year,month,quarter,orders,revenue_usd,avg_order_value,avg_discount_pct,return_rate,unique_customers,new_customers
0,2020,1,Q1,266,35415.25,133.14,5.68,0.0,261,100
1,2020,2,Q1,268,34304.78,128.00,6.06,0.0,263,93
2,2020,3,Q1,258,32642.23,126.52,5.21,0.0,254,81
3,2020,4,Q2,281,34865.39,124.08,5.27,0.0,275,99
4,2020,5,Q2,286,38625.73,135.06,5.84,0.0,282,113

ORDERS

,order_id,customer_id,order_date,year,month,quarter,day_of_week,product_name,category,unit_price_usd,...,payment_method,device_used,delivery_days,delivery_date,order_status,returned,customer_rating,session_duration_minutes,pages_viewed_before_purchase,is_repeat_customer
0,O000001,C07108,2020-08-27,2020,8,Q3,Thursday,Tire Inflator,Automotive,62.91,...,Credit Card,Desktop,3,2020-08-30,Delivered,0,NaN,14.4,1,1
1,O000002,C03487,2024-04-11,2024,4,Q2,Thursday,Stud Earrings Gold,Jewelry & Accessories,18.44,...,Credit Card,Mobile,2,2024-04-13,Delivered,0,NaN,9.0,4,0
2,O000003,C03062,2023-06-25,2023,6,Q2,Sunday,Pen Set Premium,Office Supplies,109.79,...,PayPal,Desktop,3,2023-06-28,Delivered,0,4.0,3.2,17,0
3,O000004,C00888,2020-08-16,2020,8,Q3,Sunday,Smart Watch Series 5,Electronics,87.21,...,Credit Card,Tablet,2,2020-08-18,Returned,1,NaN,32.2,3,1
4,O000005,C01674,2020-04-24,2020,4,Q2,Friday,Stud Earrings Gold,Jewelry & Accessories,94.30,...,Debit Card,Mobile,5,2020-04-29,Delivered,0,2.8,54.7,2,1

PRODUCT_SUMMARY

,category,product_name,total_orders,total_revenue_usd,avg_price,avg_rating,return_rate,avg_discount_pct,avg_delivery_days
0,Automotive,Air Freshener,87,10543.38,73.61,3.95,7.0,4.54,4.66
1,Automotive,Car Phone Mount,86,10950.18,73.82,3.99,12.0,5.76,4.08
2,Automotive,Car Vacuum Cleaner,73,8588.32,71.15,4.11,7.0,7.53,4.38
3,Automotive,Dashcam 4K,79,9402.79,68.25,4.06,6.0,4.18,4.20
4,Automotive,Jump Starter Pack,68,8338.79,78.06,4.00,10.0,4.63,4.03

In [30]:
for name, df in dataframes.items():
    print(f"\n{name.upper()}")
    df.info()

CUSTOMERS
<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               8000 non-null   str
 1   country                   8000 non-null   str
 2   age                       8000 non-null   int64
 3   gender                    8000 non-null   str
 4   membership_tier           8000 non-null   str
 5   registration_date         8000 non-null   str
 6   total_orders              8000 non-null   int64
 7   total_spend_usd           8000 non-null   float64
 8   avg_order_value_usd       8000 non-null   float64
 9   days_since_last_purchase  8000 non-null   int64
 10  preferred_category        8000 non-null   str
 11  preferred_device          8000 non-null   str
 12  preferred_payment_method  8000 non-null   str
 13  acquisition_channel       8000 non-null   str
 14  reviews_given             8000 non-null   int64
 15  avg_review_score          8000 non-null   float64
 16  returns_made              8000 non-null   int64
 17  wishlist_items            8000 non-null   int64
 18  newsletter_subscribed     8000 non-null   int64
 19  churned                   8000 non-null   int64
dtypes: float64(3), int64(8), str(9)
memory usage: 1.2 MB

MONTHLY_REVENUE
<class 'pandas.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              75 non-null     int64
 1   month             75 non-null     int64
 2   quarter           75 non-null     str
 3   orders            75 non-null     int64
 4   revenue_usd       75 non-null     float64
 5   avg_order_value   75 non-null     float64
 6   avg_discount_pct  75 non-null     float64
 7   return_rate       75 non-null     float64
 8   unique_customers  75 non-null     int64
 9   new_customers     75 non-null     int64
dtypes: float64(4), int64(5), str(1)
memory usage: 6.0 KB

ORDERS
<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 28 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   order_id                      25000 non-null  str
 1   customer_id                   25000 non-null  str
 2   order_date                    25000 non-null  str
 3   year                          25000 non-null  int64
 4   month                         25000 non-null  int64
 5   quarter                       25000 non-null  str
 6   day_of_week                   25000 non-null  str
 7   product_name                  25000 non-null  str
 8   category                      25000 non-null  str
 9   unit_price_usd                25000 non-null  float64
 10  quantity                      25000 non-null  int64
 11  subtotal_usd                  25000 non-null  float64
 12  discount_pct                  25000 non-null  int64
 13  discount_amount_usd           25000 non-null  float64
 14  shipping_fee_usd              25000 non-null  float64
 15  tax_pct                       25000 non-null  int64
 16  tax_amount_usd                25000 non-null  float64
 17  total_amount_usd              25000 non-null  float64
 18  payment_method                25000 non-null  str
 19  device_used                   25000 non-null  str
 20  delivery_days                 25000 non-null  int64
 21  delivery_date                 25000 non-null  str
 22  order_status                  25000 non-null  str
 23  returned                      25000 non-null  int64
 24  customer_rating               9251 non-null   float64
 25  session_duration_minutes      25000 non-null  float64
 26  pages_viewed_before_purchase  25000 non-null  int64
 27  is_repeat_customer            25000 non-null  int64
dtypes: float64(8), int64(9), str(11)
memory usage: 5.3 MB

PRODUCT_SUMMARY
<class 'pandas.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   category           140 non-null    str
 1   product_name       140 non-null    str
 2   total_orders       140 non-null    int64
 3   total_revenue_usd  140 non-null    float64
 4   avg_price          140 non-null    float64
 5   avg_rating         140 non-null    float64
 6   return_rate        140 non-null    float64
 7   avg_discount_pct   140 non-null    float64
 8   avg_delivery_days  140 non-null    float64
dtypes: float64(6), int64(1), str(2)
memory usage: 10.0 KB

In [45]:
for name, df in dataframes.items():
    print(f"\n{name.upper()}")
    print(df.isna().sum())

CUSTOMERS
customer_id                 0
country                     0
age                         0
gender                      0
membership_tier             0
registration_date           0
total_orders                0
total_spend_usd             0
avg_order_value_usd         0
days_since_last_purchase    0
preferred_category          0
preferred_device            0
preferred_payment_method    0
acquisition_channel         0
reviews_given               0
avg_review_score            0
returns_made                0
wishlist_items              0
newsletter_subscribed       0
churned                     0
dtype: int64

MONTHLY_REVENUE
year                0
month               0
quarter             0
orders              0
revenue_usd         0
avg_order_value     0
avg_discount_pct    0
return_rate         0
unique_customers    0
new_customers       0
dtype: int64

ORDERS
order_id                            0
customer_id                         0
order_date                          0
year                                0
month                               0
quarter                             0
day_of_week                         0
product_name                        0
category                            0
unit_price_usd                      0
quantity                            0
subtotal_usd                        0
discount_pct                        0
discount_amount_usd                 0
shipping_fee_usd                    0
tax_pct                             0
tax_amount_usd                      0
total_amount_usd                    0
payment_method                      0
device_used                         0
delivery_days                       0
delivery_date                       0
order_status                        0
returned                            0
customer_rating                 15749
session_duration_minutes            0
pages_viewed_before_purchase        0
is_repeat_customer                  0
dtype: int64

PRODUCT_SUMMARY
category             0
product_name         0
total_orders         0
total_revenue_usd    0
avg_price            0
avg_rating           0
return_rate          0
avg_discount_pct     0
avg_delivery_days    0
dtype: int64

In [50]:
for name, df in dataframes.items():
    print(f"{name}:{df.duplicated().sum()} duplicate rows")

customers:0 duplicate rows
monthly_revenue:0 duplicate rows
orders:0 duplicate rows
product_summary:0 duplicate rows

In [52]:
for name, df in dataframes.items():
    print(f"{name.upper()}")
    print(df.dtypes)

CUSTOMERS
customer_id                     str
country                         str
age                           int64
gender                          str
membership_tier                 str
registration_date               str
total_orders                  int64
total_spend_usd             float64
avg_order_value_usd         float64
days_since_last_purchase      int64
preferred_category              str
preferred_device                str
preferred_payment_method        str
acquisition_channel             str
reviews_given                 int64
avg_review_score            float64
returns_made                  int64
wishlist_items                int64
newsletter_subscribed         int64
churned                       int64
dtype: object
MONTHLY_REVENUE
year                  int64
month                 int64
quarter                 str
orders                int64
revenue_usd         float64
avg_order_value     float64
avg_discount_pct    float64
return_rate         float64
unique_customers      int64
new_customers         int64
dtype: object
ORDERS
order_id                            str
customer_id                         str
order_date                          str
year                              int64
month                             int64
quarter                             str
day_of_week                         str
product_name                        str
category                            str
unit_price_usd                  float64
quantity                          int64
subtotal_usd                    float64
discount_pct                      int64
discount_amount_usd             float64
shipping_fee_usd                float64
tax_pct                           int64
tax_amount_usd                  float64
total_amount_usd                float64
payment_method                      str
device_used                         str
delivery_days                     int64
delivery_date                       str
order_status                        str
returned                          int64
customer_rating                 float64
session_duration_minutes        float64
pages_viewed_before_purchase      int64
is_repeat_customer                int64
dtype: object
PRODUCT_SUMMARY
category                 str
product_name             str
total_orders           int64
total_revenue_usd    float64
avg_price            float64
avg_rating           float64
return_rate          float64
avg_discount_pct     float64
avg_delivery_days    float64
dtype: object

In [53]:
for name, df in dataframes.items():
    print(f"{name.upper()}")
    print(df.nunique())

CUSTOMERS
customer_id                 8000
country                       20
age                           57
gender                         3
membership_tier                4
registration_date           1862
total_orders                  79
total_spend_usd             7864
avg_order_value_usd         6365
days_since_last_purchase     336
preferred_category            14
preferred_device               3
preferred_payment_method       7
acquisition_channel            6
reviews_given                 29
avg_review_score              33
returns_made                  12
wishlist_items                37
newsletter_subscribed          2
churned                        2
dtype: int64
MONTHLY_REVENUE
year                 7
month               12
quarter              4
orders              45
revenue_usd         75
avg_order_value     74
avg_discount_pct    64
return_rate          1
unique_customers    44
new_customers       32
dtype: int64
ORDERS
order_id                        25000
customer_id                      7663
order_date                       2281
year                                7
month                              12
quarter                             4
day_of_week                         7
product_name                      140
category                           14
unit_price_usd                  12013
quantity                            5
subtotal_usd                    14692
discount_pct                        9
discount_amount_usd              3636
shipping_fee_usd                    5
tax_pct                             7
tax_amount_usd                   4564
total_amount_usd                15367
payment_method                      7
device_used                         3
delivery_days                       8
delivery_date                    2290
order_status                        4
returned                            2
customer_rating                    35
session_duration_minutes          921
pages_viewed_before_purchase       24
is_repeat_customer                  2
dtype: int64
PRODUCT_SUMMARY
category              14
product_name         140
total_orders         108
total_revenue_usd    140
avg_price            137
avg_rating            40
return_rate           15
avg_discount_pct     112
avg_delivery_days     72
dtype: int64

In [34]:
customers = pd.read_csv(raw_path/ "customers.csv")
customers.head()

,customer_id,country,age,gender,membership_tier,registration_date,total_orders,total_spend_usd,avg_order_value_usd,days_since_last_purchase,preferred_category,preferred_device,preferred_payment_method,acquisition_channel,reviews_given,avg_review_score,returns_made,wishlist_items,newsletter_subscribed,churned
0,C00001,United States,40,Male,Free,2019-01-17,4,286.63,63.78,49,Food & Grocery,Mobile,Debit Card,Social Media,1,4.5,0,12,0,0
1,C00002,United States,20,Female,Free,2026-03-04,11,1245.18,107.32,126,Toys & Games,Mobile,Debit Card,Organic Search,2,2.6,1,1,0,0
2,C00003,United States,43,Female,Gold,2026-02-08,4,195.37,42.74,0,Home & Kitchen,Mobile,PayPal,Referral,0,4.8,0,0,1,0
3,C00004,United States,41,Male,Free,2025-03-19,6,99.45,15.61,6,Electronics,Desktop,PayPal,Organic Search,2,4.2,0,8,1,0
4,C00005,France,37,Other,Platinum,2024-09-10,36,2593.21,79.09,161,Clothing & Apparel,Tablet,Debit Card,Social Media,9,4.0,4,5,1,0

In [37]:
monthly_revenue = pd.read_csv(raw_path/ "monthly_revenue.csv")
monthly_revenue.head()

,year,month,quarter,orders,revenue_usd,avg_order_value,avg_discount_pct,return_rate,unique_customers,new_customers
0,2020,1,Q1,266,35415.25,133.14,5.68,0.0,261,100
1,2020,2,Q1,268,34304.78,128.00,6.06,0.0,263,93
2,2020,3,Q1,258,32642.23,126.52,5.21,0.0,254,81
3,2020,4,Q2,281,34865.39,124.08,5.27,0.0,275,99
4,2020,5,Q2,286,38625.73,135.06,5.84,0.0,282,113

In [39]:
orders = pd.read_csv(raw_path/ "orders.csv")
orders.head()

,order_id,customer_id,order_date,year,month,quarter,day_of_week,product_name,category,unit_price_usd,...,payment_method,device_used,delivery_days,delivery_date,order_status,returned,customer_rating,session_duration_minutes,pages_viewed_before_purchase,is_repeat_customer
0,O000001,C07108,2020-08-27,2020,8,Q3,Thursday,Tire Inflator,Automotive,62.91,...,Credit Card,Desktop,3,2020-08-30,Delivered,0,NaN,14.4,1,1
1,O000002,C03487,2024-04-11,2024,4,Q2,Thursday,Stud Earrings Gold,Jewelry & Accessories,18.44,...,Credit Card,Mobile,2,2024-04-13,Delivered,0,NaN,9.0,4,0
2,O000003,C03062,2023-06-25,2023,6,Q2,Sunday,Pen Set Premium,Office Supplies,109.79,...,PayPal,Desktop,3,2023-06-28,Delivered,0,4.0,3.2,17,0
3,O000004,C00888,2020-08-16,2020,8,Q3,Sunday,Smart Watch Series 5,Electronics,87.21,...,Credit Card,Tablet,2,2020-08-18,Returned,1,NaN,32.2,3,1
4,O000005,C01674,2020-04-24,2020,4,Q2,Friday,Stud Earrings Gold,Jewelry & Accessories,94.30,...,Debit Card,Mobile,5,2020-04-29,Delivered,0,2.8,54.7,2,1

In [44]:
product_summary = pd.read_csv(raw_path/ "product_summary.csv")
product_summary.head()

,category,product_name,total_orders,total_revenue_usd,avg_price,avg_rating,return_rate,avg_discount_pct,avg_delivery_days
0,Automotive,Air Freshener,87,10543.38,73.61,3.95,7.0,4.54,4.66
1,Automotive,Car Phone Mount,86,10950.18,73.82,3.99,12.0,5.76,4.08
2,Automotive,Car Vacuum Cleaner,73,8588.32,71.15,4.11,7.0,7.53,4.38
3,Automotive,Dashcam 4K,79,9402.79,68.25,4.06,6.0,4.18,4.20
4,Automotive,Jump Starter Pack,68,8338.79,78.06,4.00,10.0,4.63,4.03

In [55]:
customers.columns.intersection(orders.columns).tolist()

['customer_id']

In [56]:
customers["customer_id"].duplicated().sum()

np.int64(0)

In [57]:
customers["customer_id"].nunique()

8000

In [58]:
len(customers)

8000

In [59]:
orders["customer_id"].nunique()

7663

In [63]:
orders[~orders["customer_id"].isin(customers["customer_id"])]["customer_id"].nunique()

0

In [66]:
orders.columns.tolist()

['order_id',
 'customer_id',
 'order_date',
 'year',
 'month',
 'quarter',
 'day_of_week',
 'product_name',
 'category',
 'unit_price_usd',
 'quantity',
 'subtotal_usd',
 'discount_pct',
 'discount_amount_usd',
 'shipping_fee_usd',
 'tax_pct',
 'tax_amount_usd',
 'total_amount_usd',
 'payment_method',
 'device_used',
 'delivery_days',
 'delivery_date',
 'order_status',
 'returned',
 'customer_rating',
 'session_duration_minutes',
 'pages_viewed_before_purchase',
 'is_repeat_customer']

In [64]:
monthly_revenue.columns.tolist()

['year',
 'month',
 'quarter',
 'orders',
 'revenue_usd',
 'avg_order_value',
 'avg_discount_pct',
 'return_rate',
 'unique_customers',
 'new_customers']

In [65]:
product_summary.columns.tolist()

['category',
 'product_name',
 'total_orders',
 'total_revenue_usd',
 'avg_price',
 'avg_rating',
 'return_rate',
 'avg_discount_pct',
 'avg_delivery_days']